LVR Update
naturerobots/mesh_navigation pull request #70
Opened 2024-12-11 23:27 UTC by amock

This is a reaction to the upcoming LVR update (3.0.0). It contains two major changes:

### Interchangable Half-Edge-Mesh

The map and all plugins only use the BaseMesh from LVR. This means that as long as you implement the BaseMesh interface of LVR, you can use any half-edge mesh implementation you want. The implementations can be selected with a new ROS parameter “hem” (Half-Edge-Mesh). "hem: pmp" or "hem: lvr" ist possible. If no parameter is specified the new pmp mesh is chosen. The old behavior can be restored by setting "hem" to "lvr". The pmp mesh turned out to be much more robust to load any mesh coming from other meshing software than lvr (such as meshlab or Open3D). Internally, I used a smart pointer to handle the BaseMesh because it makes things easier. 

### Loading/Writing HDF5

The HDF5 structure has changed slightly over time so that the description of the mesh_tools paper is not valid anymore. I changed parts of it back so that it gets more like the papers again. It also makes things easier to handle since vertex attributes are now separated from the actual mesh geometry inside the HDF5.

### Cleanup

I have also removed packages for which we have no tests and which are not currently used anywhere:
- mesh_msgs_hdf5
- hdf5_map_io

### Testing instructions

This PR works together with:
- [lvr2](https://github.com/uos/lvr2/tree/version-upgrade) - branch: version-upgrade
- [mesh_tools](https://github.com/naturerobots/mesh_tools/tree/lvr-update) - branch: lvr-update

I have a working version of mesh_navigation_tutorials for which I will make a PR soon so that you can test all the changes.

2024-12-20 14:06 UTC, Cakem1x requested changes
Please double check some of the logging statements. Other than that, it looks good!

However, CI seems to disagree with some of the change. As soon as CI is fine, I think we can merge.

2024-12-23 11:41 UTC, amock commented on cvp_mesh_planner/src/cvp_mesh_planner.cpp
> +  RCLCPP_DEBUG_STREAM(node_->get_logger(), "GO.");
It's removed now

2024-12-23 11:42 UTC, amock commented on cvp_mesh_planner/src/cvp_mesh_planner.cpp
> +  RCLCPP_DEBUG_STREAM(node_->get_logger(), "BLA 2.");
I accidentally left those there :) They are all removed now

2024-12-23 12:00 UTC, amock commented
> Please double check some of the logging statements. Other than that, it looks good!
> 
> However, CI seems to disagree with some of the change. As soon as CI is fine, I think we can merge.

All tests are now running without errors :+1:

2025-01-02 08:27 UTC, Cakem1x approved these changes
Great :)

2025-01-02 11:38 UTC, merged